apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-rabbitmq
  namespace: vprofile

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vprofile-rabbitmq

  template:
    metadata:
      labels:
        app: vprofile-rabbitmq

    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management

          ports:
            - containerPort: 5672
            - containerPort: 15672

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"