apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-db
  namespace: vprofile

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vprofile-db

  template:
    metadata:
      labels:
        app: vprofile-db

    spec:
      containers:
      - name:  mysql
         image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root   